#!/usr/bin/env bun

import fs from "fs"
import path from "path"

const dir = path.resolve(import.meta.dir, "..")
const snapshotPath = path.join(dir, "src/provider/models-snapshot.ts")
const modelsUrl = process.env.HOPCODERX_MODELS_URL || "https://models.dev"

let modelsData: string
try {
  modelsData = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
} catch (err) {
  console.warn("Failed to fetch models snapshot, using empty fallback:", err)
  modelsData = '{"providers":{}}'
}

const nextContent = `// Auto-generated by models-snapshot.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`
const previousContent = fs.existsSync(snapshotPath) ? await Bun.file(snapshotPath).text() : undefined

if (previousContent !== nextContent) {
  await Bun.write(snapshotPath, nextContent)
  console.log("Updated models-snapshot.ts")
} else {
  console.log("models-snapshot.ts already up to date")
}

