name: hopcoderx

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  hopcoderx:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /hopcoderx') ||
      startsWith(github.event.comment.body, '/hopcoderx')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run hopcoderx
        uses: TaimoorSiddiquiOfficial/hopcoderx/github@latest
        env:
          HOPCODERX_API_KEY: ${{ secrets.HOPCODERX_API_KEY }}
          HOPCODERX_PERMISSION: '{"bash": "deny"}'
        with:
          model: hopcoderx/claude-opus-4-5
